### ISSUE TITLE
又一个骗星星的项目

### ISSUE THREAD

**Issue by yinjun322** [Teameeting/Teameeting-Android#2]
又一个骗星星的项目

**Comment by DyncLang** [comment]
怎么理解?哥们有问题你可以说嘛。虚心修改。

**Comment by yinjun322** [comment]
真正核心的应该是so吧，貌似并不开源
难道我没找到⊙﹏⊙b汗

**Comment by DyncLang** [comment]
我们不是普及我们的技术, 是希望你能简单的使用我们的技术.   如果哥们真的感兴趣, 可以联系我们. 给你提供技术支持.
